version: "1.0" # Updated to a valid version

services:
  server:
    tty: true
    container_name: itrum_task
    image: itrum_task:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .files:/app/files
    depends_on:
      database:
        condition: service_healthy
    networks:
      - itrum_task-network
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/healthcheck"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3

  database:
    container_name: database
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: itrum_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
    restart: always
    volumes:
      - itrum_task:/var/lib/postgresql/data
    networks:
      - itrum_task-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"] # Check if PostgreSQL is ready
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  itrum_task:
    name: itrum_task

networks:
  itrum_task-network:
    driver: bridge
