"""empty message

Revision ID: 665b3ff07cd5
Revises: 
Create Date: 2025-06-25 21:08:56.197872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665b3ff07cd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdivisions',
    sa.Column('subdivision_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4086), server_default='NULL', nullable=True),
    sa.Column('creation_time', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('department', sa.Enum('PUBLIC_SAFETY', 'TRANSPORTATION', 'PARKS_RECREATION', 'ENVIRONMENTAL', 'HEALTH_HUMAN', 'PLANNING_DEVELOPMENT', 'EDUCATION', 'ADMINISTRATIVE', 'HOUSING', 'ECONOMIC_DEVELOPMENT', 'UTILITIES', 'CULTURAL_AFFAIRS', 'ANIMAL_SERVICES', 'DISABILITY_SERVICES', 'TECHNOLOGY', name='departmentenum'), nullable=False),
    sa.PrimaryKeyConstraint('subdivision_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('avatar')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('employees',
    sa.Column('employee', sa.String(), nullable=False),
    sa.Column('department', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department'], ['subdivisions.subdivision_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee', 'department')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('complete_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=2048), server_default='NULL', nullable=True),
    sa.Column('subdivision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivisions.subdivision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subdivisions')
    # ### end Alembic commands ###
