"""empty message

Revision ID: 4c24f65f3ae7
Revises: 2018124fd0ef
Create Date: 2025-06-29 16:06:58.440551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c24f65f3ae7'
down_revision: Union[str, Sequence[str], None] = '2018124fd0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('subdivision', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('employees_department_fkey'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('employees_employee_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'subdivisions', ['subdivision'], ['subdivision_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employees', 'users', ['user'], ['username'], ondelete='CASCADE')
    op.drop_column('employees', 'employee')
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('employee', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_employee_fkey'), 'employees', 'users', ['employee'], ['username'], ondelete='CASCADE')
    op.create_foreign_key(op.f('employees_department_fkey'), 'employees', 'subdivisions', ['department'], ['subdivision_id'], ondelete='CASCADE')
    op.drop_column('employees', 'subdivision')
    op.drop_column('employees', 'user')
    # ### end Alembic commands ###
